### PR TITLE
Add support for different project assemblyname

### PR DESCRIPTION
**Pull request by jeppevammenkristensen**
In some scenarios where a different assembly name has been set, instead of the project name, the project would not be found. This addition adds an additional check if we have not allready matched a project, where we try to get the assembly name and compare that to the assembly name to search for

### CODE REVIEW

**Review by ycherkes — COMMENTED** [review]
Hi @jeppevammenkristensen.
Thank you for your contribution. I just totally changed the way how to determine the TargetFramework. 
Could you please verify, that the new approach is working for you?
[438604ef9ecbe27a9abb7c7d971bca520df9e66c](https://github.com/ycherkes/ObjectDumper/commit/438604ef9ecbe27a9abb7c7d971bca520df9e66c)

**Comment by jeppevammenkristensen** [comment]
I'll get the latest update and check

**Comment by jeppevammenkristensen** [comment]
I'm closing the pullrequest. I can see that in the new version it's not necesarry to query for Project info. I verified that it works as expected when the assembly name and project name does not match.

**Comment by ycherkes** [comment]
Great to hear it. Thank you!

**Pull request closed without merging**
